INSERT INTO municipio VALUES (0, 'Abaiara', 6);
INSERT INTO municipio VALUES (0, 'Acarape', 6);
INSERT INTO municipio VALUES (0, 'Acaraú', 6);
INSERT INTO municipio VALUES (0, 'Acopiara', 6);
INSERT INTO municipio VALUES (0, 'Aiuaba', 6);
INSERT INTO municipio VALUES (0, 'Alcântaras', 6);
INSERT INTO municipio VALUES (0, 'Altaneira', 6);
INSERT INTO municipio VALUES (0, 'Alto Santo', 6);
INSERT INTO municipio VALUES (0, 'Amontada', 6);
INSERT INTO municipio VALUES (0, 'Antonina do Norte', 6);
INSERT INTO municipio VALUES (0, 'Apuiarés', 6);
INSERT INTO municipio VALUES (0, 'Aquiraz', 6);
INSERT INTO municipio VALUES (0, 'Aracati', 6);
INSERT INTO municipio VALUES (0, 'Aracoiaba', 6);
INSERT INTO municipio VALUES (0, 'Ararendá', 6);
INSERT INTO municipio VALUES (0, 'Araripe', 6);
INSERT INTO municipio VALUES (0, 'Aratuba', 6);
INSERT INTO municipio VALUES (0, 'Arneiroz', 6);
INSERT INTO municipio VALUES (0, 'Assaré', 6);
INSERT INTO municipio VALUES (0, 'Aurora', 6);
INSERT INTO municipio VALUES (0, 'Baixio', 6);
INSERT INTO municipio VALUES (0, 'Banabuiú', 6);
INSERT INTO municipio VALUES (0, 'Barbalha', 6);
INSERT INTO municipio VALUES (0, 'Barreira', 6);
INSERT INTO municipio VALUES (0, 'Barro', 6);
INSERT INTO municipio VALUES (0, 'Barroquinha', 6);
INSERT INTO municipio VALUES (0, 'Baturité', 6);
INSERT INTO municipio VALUES (0, 'Beberibe', 6);
INSERT INTO municipio VALUES (0, 'Bela Cruz', 6);
INSERT INTO municipio VALUES (0, 'Boa Viagem', 6);
INSERT INTO municipio VALUES (0, 'Brejo Santo', 6);
INSERT INTO municipio VALUES (0, 'Camocim', 6);
INSERT INTO municipio VALUES (0, 'Campos Sales', 6);
INSERT INTO municipio VALUES (0, 'Canindé', 6);
INSERT INTO municipio VALUES (0, 'Capistrano', 6);
INSERT INTO municipio VALUES (0, 'Caridade', 6);
INSERT INTO municipio VALUES (0, 'Cariré', 6);
INSERT INTO municipio VALUES (0, 'Caririaçu', 6);
INSERT INTO municipio VALUES (0, 'Cariús', 6);
INSERT INTO municipio VALUES (0, 'Carnaubal', 6);
INSERT INTO municipio VALUES (0, 'Cascavel', 6);
INSERT INTO municipio VALUES (0, 'Catarina', 6);
INSERT INTO municipio VALUES (0, 'Catunda', 6);
INSERT INTO municipio VALUES (0, 'Caucaia', 6);
INSERT INTO municipio VALUES (0, 'Cedro', 6);
INSERT INTO municipio VALUES (0, 'Chaval', 6);
INSERT INTO municipio VALUES (0, 'Choró', 6);
INSERT INTO municipio VALUES (0, 'Chorozinho', 6);
INSERT INTO municipio VALUES (0, 'Coreaú', 6);
INSERT INTO municipio VALUES (0, 'Crateús', 6);
INSERT INTO municipio VALUES (0, 'Crato', 6);
INSERT INTO municipio VALUES (0, 'Croatá', 6);
INSERT INTO municipio VALUES (0, 'Cruz', 6);
INSERT INTO municipio VALUES (0, 'Deputado Irapuan Pinheiro', 6);
INSERT INTO municipio VALUES (0, 'Ererê', 6);
INSERT INTO municipio VALUES (0, 'Eusébio', 6);
INSERT INTO municipio VALUES (0, 'Farias Brito', 6);
INSERT INTO municipio VALUES (0, 'Forquilha', 6);
INSERT INTO municipio VALUES (0, 'Fortaleza', 6);
INSERT INTO municipio VALUES (0, 'Fortim', 6);
INSERT INTO municipio VALUES (0, 'Frecheirinha', 6);
INSERT INTO municipio VALUES (0, 'General Sampaio', 6);
INSERT INTO municipio VALUES (0, 'Graça', 6);
INSERT INTO municipio VALUES (0, 'Granja', 6);
INSERT INTO municipio VALUES (0, 'Granjeiro', 6);
INSERT INTO municipio VALUES (0, 'Groaíras', 6);
INSERT INTO municipio VALUES (0, 'Guaiúba', 6);
INSERT INTO municipio VALUES (0, 'Guaraciaba do Norte', 6);
INSERT INTO municipio VALUES (0, 'Guaramiranga', 6);
INSERT INTO municipio VALUES (0, 'Hidrolândia', 6);
INSERT INTO municipio VALUES (0, 'Horizonte', 6);
INSERT INTO municipio VALUES (0, 'Ibaretama', 6);
INSERT INTO municipio VALUES (0, 'Ibiapina', 6);
INSERT INTO municipio VALUES (0, 'Ibicuitinga', 6);
INSERT INTO municipio VALUES (0, 'Icapuí', 6);
INSERT INTO municipio VALUES (0, 'Icó', 6);
INSERT INTO municipio VALUES (0, 'Iguatu', 6);
INSERT INTO municipio VALUES (0, 'Independência', 6);
INSERT INTO municipio VALUES (0, 'Ipaporanga', 6);
INSERT INTO municipio VALUES (0, 'Ipaumirim', 6);
INSERT INTO municipio VALUES (0, 'Ipu', 6);
INSERT INTO municipio VALUES (0, 'Ipueiras', 6);
INSERT INTO municipio VALUES (0, 'Iracema', 6);
INSERT INTO municipio VALUES (0, 'Irauçuba', 6);
INSERT INTO municipio VALUES (0, 'Itaiçaba', 6);
INSERT INTO municipio VALUES (0, 'Itaitinga', 6);
INSERT INTO municipio VALUES (0, 'Itapajé', 6);
INSERT INTO municipio VALUES (0, 'Itapipoca', 6);
INSERT INTO municipio VALUES (0, 'Itapiúna', 6);
INSERT INTO municipio VALUES (0, 'Itarema', 6);
INSERT INTO municipio VALUES (0, 'Itatira', 6);
INSERT INTO municipio VALUES (0, 'Jaguaretama', 6);
INSERT INTO municipio VALUES (0, 'Jaguaribara', 6);
INSERT INTO municipio VALUES (0, 'Jaguaribe', 6);
INSERT INTO municipio VALUES (0, 'Jaguaruana', 6);
INSERT INTO municipio VALUES (0, 'Jardim', 6);
INSERT INTO municipio VALUES (0, 'Jati', 6);
INSERT INTO municipio VALUES (0, 'Jijoca de Jericoacoara', 6);
INSERT INTO municipio VALUES (0, 'Juazeiro do Norte', 6);
INSERT INTO municipio VALUES (0, 'Jucás', 6);
INSERT INTO municipio VALUES (0, 'Lavras da Mangabeira', 6);
INSERT INTO municipio VALUES (0, 'Limoeiro do Norte', 6);
INSERT INTO municipio VALUES (0, 'Madalena', 6);
INSERT INTO municipio VALUES (0, 'Maracanaú', 6);
INSERT INTO municipio VALUES (0, 'Maranguape', 6);
INSERT INTO municipio VALUES (0, 'Marco', 6);
INSERT INTO municipio VALUES (0, 'Martinópole', 6);
INSERT INTO municipio VALUES (0, 'Massapê', 6);
INSERT INTO municipio VALUES (0, 'Mauriti', 6);
INSERT INTO municipio VALUES (0, 'Meruoca', 6);
INSERT INTO municipio VALUES (0, 'Milagres', 6);
INSERT INTO municipio VALUES (0, 'Milhã', 6);
INSERT INTO municipio VALUES (0, 'Miraíma', 6);
INSERT INTO municipio VALUES (0, 'Missão Velha', 6);
INSERT INTO municipio VALUES (0, 'Mombaça', 6);
INSERT INTO municipio VALUES (0, 'Monsenhor Tabosa', 6);
INSERT INTO municipio VALUES (0, 'Morada Nova', 6);
INSERT INTO municipio VALUES (0, 'Moraújo', 6);
INSERT INTO municipio VALUES (0, 'Morrinhos', 6);
INSERT INTO municipio VALUES (0, 'Mucambo', 6);
INSERT INTO municipio VALUES (0, 'Mulungu', 6);
INSERT INTO municipio VALUES (0, 'Nova Olinda', 6);
INSERT INTO municipio VALUES (0, 'Nova Russas', 6);
INSERT INTO municipio VALUES (0, 'Novo Oriente', 6);
INSERT INTO municipio VALUES (0, 'Ocara', 6);
INSERT INTO municipio VALUES (0, 'Orós', 6);
INSERT INTO municipio VALUES (0, 'Pacajus', 6);
INSERT INTO municipio VALUES (0, 'Pacatuba', 6);
INSERT INTO municipio VALUES (0, 'Pacoti', 6);
INSERT INTO municipio VALUES (0, 'Pacujá', 6);
INSERT INTO municipio VALUES (0, 'Palhano', 6);
INSERT INTO municipio VALUES (0, 'Palmácia', 6);
INSERT INTO municipio VALUES (0, 'Paracuru', 6);
INSERT INTO municipio VALUES (0, 'Paraipaba', 6);
INSERT INTO municipio VALUES (0, 'Parambu', 6);
INSERT INTO municipio VALUES (0, 'Paramoti', 6);
INSERT INTO municipio VALUES (0, 'Pedra Branca', 6);
INSERT INTO municipio VALUES (0, 'Penaforte', 6);
INSERT INTO municipio VALUES (0, 'Pentecoste', 6);
INSERT INTO municipio VALUES (0, 'Pereiro', 6);
INSERT INTO municipio VALUES (0, 'Pindoretama', 6);
INSERT INTO municipio VALUES (0, 'Piquet Carneiro', 6);
INSERT INTO municipio VALUES (0, 'Pires Ferreira', 6);
INSERT INTO municipio VALUES (0, 'Poranga', 6);
INSERT INTO municipio VALUES (0, 'Porteiras', 6);
INSERT INTO municipio VALUES (0, 'Potengi', 6);
INSERT INTO municipio VALUES (0, 'Potiretama', 6);
INSERT INTO municipio VALUES (0, 'Quiterianópolis', 6);
INSERT INTO municipio VALUES (0, 'Quixadá', 6);
INSERT INTO municipio VALUES (0, 'Quixelô', 6);
INSERT INTO municipio VALUES (0, 'Quixeramobim', 6);
INSERT INTO municipio VALUES (0, 'Quixeré', 6);
INSERT INTO municipio VALUES (0, 'Redenção', 6);
INSERT INTO municipio VALUES (0, 'Reriutaba', 6);
INSERT INTO municipio VALUES (0, 'Russas', 6);
INSERT INTO municipio VALUES (0, 'Saboeiro', 6);
INSERT INTO municipio VALUES (0, 'Salitre', 6);
INSERT INTO municipio VALUES (0, 'Santa Quitéria', 6);
INSERT INTO municipio VALUES (0, 'Santana do Acaraú', 6);
INSERT INTO municipio VALUES (0, 'Santana do Cariri', 6);
INSERT INTO municipio VALUES (0, 'São Benedito', 6);
INSERT INTO municipio VALUES (0, 'São Gonçalo do Amarante', 6);
INSERT INTO municipio VALUES (0, 'São João do Jaguaribe', 6);
INSERT INTO municipio VALUES (0, 'São Luís do Curu', 6);
INSERT INTO municipio VALUES (0, 'Senador Pompeu', 6);
INSERT INTO municipio VALUES (0, 'Senador Sá', 6);
INSERT INTO municipio VALUES (0, 'Sobral', 6);
INSERT INTO municipio VALUES (0, 'Solonópole', 6);
INSERT INTO municipio VALUES (0, 'Tabuleiro do Norte', 6);
INSERT INTO municipio VALUES (0, 'Tamboril', 6);
INSERT INTO municipio VALUES (0, 'Tarrafas', 6);
INSERT INTO municipio VALUES (0, 'Tauá', 6);
INSERT INTO municipio VALUES (0, 'Tejuçuoca', 6);
INSERT INTO municipio VALUES (0, 'Tianguá', 6);
INSERT INTO municipio VALUES (0, 'Trairi', 6);
INSERT INTO municipio VALUES (0, 'Tururu', 6);
INSERT INTO municipio VALUES (0, 'Ubajara', 6);
INSERT INTO municipio VALUES (0, 'Umari', 6);
INSERT INTO municipio VALUES (0, 'Umirim', 6);
INSERT INTO municipio VALUES (0, 'Uruburetama', 6);
INSERT INTO municipio VALUES (0, 'Uruoca', 6);
INSERT INTO municipio VALUES (0, 'Varjota', 6);
INSERT INTO municipio VALUES (0, 'Várzea Alegre', 6);
INSERT INTO municipio VALUES (0, 'Viçosa do Ceará', 6);